version: {build}
max_jobs: 1
configuration: Release
clone_depth: 50
before_build:
- cmd: bootstrap.bat
build:
  project: Hearthstone Collection Tracker.sln
  verbosity: minimal
artifacts:
- path: Hearthstone Collection Tracker\bin\Release\HearthstoneCollectionTracker.dll
  name: Release-dll
- path: Hearthstone Collection Tracker\bin\Debug\HearthstoneCollectionTracker.dll
  name: Debug-dll
